[theme]
theme = "solarized-light"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "

[[block]]
block = "net"
device = 'br\-[0-9a-f]{12}'
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui "

[[block]]
block = "net"
device = 'docker\d+'
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui "

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total($mem_used_percents) "
format_alt = "$icon $swap_used/$swap_total($swap_used_percents) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"

[[block]]
block = "backlight"
minimum = 20
maximum = 100
cycle = [100, 75, 50, 25]

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "$icon $used/$total ($available) "
alert = 90.0
warning = 80.0

[[block]]
block = "pacman"
interval = 600
format = " $pacman updates available "
format_singular = " $pacman update available "
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block = "uptime"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d/%m %R')"
timezone = "Europe/Prague"
interval = 7

[[block]]
block = "custom"
command = "echo \uf011"
interval = "once"
